version: '2'

services:

  tester:
    build: ./
    environment:
      HTTP_URL: 'http://ws-frontend:3000'
      WS_URL: 'ws://ws-frontend:3000'
      MAX_TIME_SECONDS: 10
    volumes:
      - ./:/app